# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install dependencies
    # set up conda
#      uses: s-weigand/setup-conda@v1.0.5
#      with:
#        conda-channels: bioconda
      uses: actions/checkout@v2
    # install dependencies
    - run: conda env create -f SubPhaser.yaml

    - name: activate
       uses: s-weigand/setup-conda@v1.0.5
    - run: conda activate SubPhaser
      
    - name: Install SubPhaser
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2
    # install TEsorter
    - run: python setup.py install
    
    - name: run test
    # run test 
      run: cd example_data
    - name: test
      run: bash test_Arabidopsis.sh
      
